### PR TITLE
Actual tandem display

### PR DESCRIPTION
**Pull request by nsmela**
Show Tandem in the export view now shows the expected tandem, not the tandem tool shape

### CODE REVIEW

**Review by michaelwkudla — CHANGES_REQUESTED** [review]
Looks really good! A couple more improvements are needed though: 

1. Change the tandem color to transparent silver in the exports view
2. Change the tandem preview so it also shows the tip diameter (the stopper diameter)
3. Change the term "Tip Diameter" to "Stopper Diameter".

**Comment by nsmela** [comment]
Changes implemented

**Comment by michaelwkudla** [comment]
I don't think number 2 is has been done yet!
2. Change the tandem preview so it also shows the tip diameter (the stopper diameter)
(For example, if I do a 4mm tandem, with a 8mm stopper, it should show both in the preview, so the user sees the stopper there too. Right now it just shows a 4mm tandem in this example. )

**Comment by nsmela** [comment]
Changes made.

**Pull request merged**
